image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install

lint:
  stage: test
  script:
    - npm run lint:prettier
    - npm run lint:js
  tags:
    - docker

unit:
  stage: test
  script:
    - npm run test:coverage
  tags:
    - docker
