language: node_js
node_js:
  - 14
  - 12
  - 10
script:
  - npm run test:tav
jobs:
  include:
    - stage: lint
      script:
        - npm run lint:commit-travis
        - npm run lint:prettier
        - npm run lint:js
    - stage: coverage
      script:
        - npm run test:coverage
        - npm run codecov
    - stage: release
      script: skip
      deploy:
        skip_cleanup: true
        provider: script
        script: npm run semantic-release
        on:
          branch: master
stages:
  - lint
  - test
  - coverage
  - release
